title: AI-Powered Development Workflow
description: Complete framework for AI-assisted development
baseurl: "/ai-development-workflow"
url: "https://joe-glasgow.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Collections
collections:
  templates:
    output: true
    permalink: /templates/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile.lock
  - .gitignore
  - README.md
